name: Simulation Regression Test (Master)

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  simualation_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
      - name: Run simulation on previous issue seeds
        run: |
          export CPU_PROFILE=0
          export HEAP_PROFILE=0
          export REPLICA_DEBUG=-1
          export CLIENT_DEBUG=-1
          export SIMULATOR_DEBUG=0
          cat records/regression_seeds | xargs go run ./cmd/simulator