name: Continuous Simulation

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */3 * * *'
  workflow_dispatch:

jobs:
  simualation_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
      - name: Run simulation
        id: run_simulation
        run: |
          export CPU_PROFILE=0
          export HEAP_PROFILE=0
          export REPLICA_DEBUG=-1
          export CLIENT_DEBUG=-1
          export SIMULATOR_DEBUG=0
          timeout 3h go run ./cmd/simulator
          if [ $? -eq 124 ]; then
            echo "Simulation timed out"
            FAIL=2
          elif [ $? -eq 0 ]; then
            echo "Simulation finished"
          else
            echo "Simulation failed"
            FAIL=1
          fi
          echo "seed=${SEED}" >> $GITHUB_OUTPUT
          echo "output=${FAIL}" >> $GITHUB_OUTPUT
      - name: Open Issue if failed
        if: ${{ steps.run_simulation.outputs.output == 1 }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEED: ${{ steps.run_simulation.outputs.seed }}
        with:
          filename: .github/templates/issues/simulation_fail.md
      - name: Open Issue if timeout
        if: ${{ steps.run_simulation.outputs.output == 2 }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEED: ${{ steps.run_simulation.outputs.seed }}
        with:
          filename: .github/templates/issues/simulation_timeout.md