name: Continuous Simulation

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/10 * * * *'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  simualation_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
      - name: Run simulation
        id: run_simulation
        run: |
          set +e
          export CPU_PROFILE=0
          export HEAP_PROFILE=0
          export REPLICA_DEBUG=-1
          export CLIENT_DEBUG=-1
          export SIMULATOR_DEBUG=0
          timeout 3h go run ./cmd/simulator
          exit_code=$?
          if [ $exit_code -eq 124 ]; then echo "Simulation timed out"; FAIL=2
          elif [ $exit_code -eq 0 ]; then echo "Simulation finished";
          else echo "Simulation failed"; FAIL=1
          fi
          echo "seed=${SEED}" >> $GITHUB_OUTPUT
          echo "output=${FAIL}" >> $GITHUB_OUTPUT
      - name: GH API open issue if failed
        uses: octokit/request-action@v2.x
        if: ${{ steps.run_simulation.outputs.output == 1 }}
        with:
          route: POST /repos/{owner}/{repo}/issues
          owner: tangledbytes
          repo: go-vsr
          title: Simulation failed for seed `${{ steps.run_simulation.outputs.seed }}`
          labels: "auto-simulation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: GH API open issue if timedout
        uses: octokit/request-action@v2.x
        if: ${{ steps.run_simulation.outputs.output == 2 }}
        with:
          route: POST /repos/{owner}/{repo}/issues
          owner: tangledbytes
          repo: go-vsr
          title: Simulation timedout for seed `${{ steps.run_simulation.outputs.seed }}`
          labels: "auto-simulation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}